
spring:
  application:
    name: Blog_provider
  rabbitmq:
    username: ${user}
    password: ${password}
    virtual-host: /
    host: ${ip}
    port: ${port}
    publisher-confirm-type: correlated
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: ${user}
    password: ${password}
    url: jdbc:mysql://${ip}/${数据库}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  redis:
    host: ${ip}
    port: ${port}
    password: ${password}


mybatis-plus:
  type-aliases-package: com.lam.model.entity
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: ${eurekaip}
  instance:
    instance-id: Blog_provider
